[package]
<<<<<<< HEAD
name = "DoasEdit"
=======
name = "doas_edit"
>>>>>>> c698b64 (Fixes identity crisis)
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.5.0"
diff = "0.1.13"
fs_extra = "1.3.0"
duct = "0.13.6"


[[bin]]
name = "doasedit"
path = "src/main.rs"
